// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest
// DO NOT EDIT. ANY CHANGES WILL BE LOST

##foreach $(project.interfaces)
#include "$(interface.name)Entities.h"
##endfor
